import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles/style.css";
import "../../styles/globals.css";
import localFont from "next/font/local";

const lato = localFont({
  src: [
    { 
      path : '../../assets/fonts/Lato/Lato-Regular.ttf', 
      weight: '400', 
      style: 'normal'
    }],
  variable: '--font-lato', 
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
