import type { Metadata } from "next";
import "./styles/style.css";
import "../styles/globals.css";
import localFont from 'next/font/local';

const tiltWarp = localFont({
  src: [
    {
      path: '../assets/fonts/TiltWarp.ttf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-tilt-warp', 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className={tiltWarp.variable}>
      <body>
        {children}
      </body>
    </html>
  );
}
