import type { Metadata } from "next";
import "./styles/globals.css";
import localFont from 'next/font/local';

const tiltWarp = localFont({
  src: [
    {
      path: './assets/fonts/TiltWarp.ttf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-tilt-warp', 
});

const lato = localFont({
  src: [
    { 
      path : './assets/fonts/Lato/Lato-Regular.ttf', 
      weight: '400', 
      style: 'normal'
    }],
  variable: '--font-lato', 
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className={`${tiltWarp.variable} ${lato.variable}`}>
      <body>
        {children}
      </body>
    </html>
  );
}
